// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVP_3n29hBabUd47KKRBwfUDNF2-gqKQc',
    appId: '1:412879879438:web:e5ef7ea1b0851e42542b5f',
    messagingSenderId: '412879879438',
    projectId: 'authtut-8c83c',
    authDomain: 'authtut-8c83c.firebaseapp.com',
    storageBucket: 'authtut-8c83c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKQUTpefx-P6l-v1RwEwgvxl2T9aEUOME',
    appId: '1:412879879438:android:614ba325b407a9db542b5f',
    messagingSenderId: '412879879438',
    projectId: 'authtut-8c83c',
    storageBucket: 'authtut-8c83c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYtiGuocgiiHz5pmyFnmap0mmnklLfA5w',
    appId: '1:412879879438:ios:872eb655d34a9de3542b5f',
    messagingSenderId: '412879879438',
    projectId: 'authtut-8c83c',
    storageBucket: 'authtut-8c83c.appspot.com',
    androidClientId: '412879879438-r9t694jvnh6jiejia3umot6n24eef6ks.apps.googleusercontent.com',
    iosClientId: '412879879438-gskd4q7t8isbnre2hhj12jj9go4b09kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYtiGuocgiiHz5pmyFnmap0mmnklLfA5w',
    appId: '1:412879879438:ios:d5008a1285ed4902542b5f',
    messagingSenderId: '412879879438',
    projectId: 'authtut-8c83c',
    storageBucket: 'authtut-8c83c.appspot.com',
    androidClientId: '412879879438-r9t694jvnh6jiejia3umot6n24eef6ks.apps.googleusercontent.com',
    iosClientId: '412879879438-9haegtd2kujjphim0sdqo35bm7heh6dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
